/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bts_pcbassistant_parsing_BoardParser */

#ifndef _Included_bts_pcbassistant_parsing_BoardParser
#define _Included_bts_pcbassistant_parsing_BoardParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bts_pcbassistant_parsing_BoardParser
 * Method:    Native
 * Signature: (Ljava/lang/String;)Lbts/pcbassistant/drawing/templates/Template;
 */
JNIEXPORT jobject JNICALL Java_bts_pcbassistant_parsing_BoardParser_Native
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
