<?php

$keep = [
	'bts',
	'pcbassistant',
	'drawing',
	'data',
	'java',
	'android',
	'final',
	'public',
	'private',
	'protected',
	'import',
	'return',
	'class',
	'null',
	'enum',
	'static',
	'this',
	'super',
	'void',
	'Override',
	'Nullable',
	'Context',
	'AttributeSet',
	'Background',
	'UiThread',
	'AfterViews',
	'ViewById',
	'EFragment',
	'dropbox:',
	'EActivity',
	'String',
	'http',
	'utf-8',
	//'http://xmlpull.org/v1/doc/features.html#process-namespaces',
	//'http://brak-tu-sensu.pl/apk/ver.php',
	'\"left\"',
	'\"top\"',
	'\"bottom\"',
	'\"right\"',
	//'R.styleable.EagleView',	
	//'EagleView_type',
	'R.styleable.MyCustomView',
	'android.graphics.Paint.Align',
	'layer-list',
	'ContextCompat.getColor',
	'bts.pcbassistant.layers',
	'android:background',
	'Select visible layers',
	'Part: ',
	//'"layer"',
	//'"smashed"',
	//	'"roundness"',
	'com.bornander.gestures.TouchManager',
	'com.dropbox.core',
];